name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit alive"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MikeStrusz/Music_Taste_Machine_Learning_Model.git HEAD:main
