name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull, commit, and push
        run: |
          git pull origin main --rebase
          git commit --allow-empty -m "Keep Streamlit alive"
          git push origin main
